### ISSUE TITLE
云函数报错

### ISSUE THREAD

**Issue by ajmhsa** [chinnkarahoi/jd_scripts#2]
![1](https://user-images.githubusercontent.com/82091617/113904542-bc37d980-9804-11eb-92ee-59c0e57b07a3.png)
请问部署到云函数运行全都显示这个，是哪里的问题啊。

**Comment by kirito8** [comment]
> ![1](https://user-images.githubusercontent.com/82091617/113904542-bc37d980-9804-11eb-92ee-59c0e57b07a3.png)
> 请问部署到云函数运行全都显示这个，是哪里的问题啊。

请问老哥是怎么解决的，我也遇到了同样的问题
