### ISSUE TITLE
我真的服了这群人

### ISSUE THREAD

**Issue by githubwyj** [chinnkarahoi/jd_scripts#29]
自己玩一下就好了
靠这个挣钱就过分了
做人无底线,废物!

**Comment by AceLin1994** [comment]
有人卖这个东西吗？

**Comment by 86xqs** [comment]
是不是有人搞破坏呀，不是作者删的呀

**Comment by githubwyj** [comment]
> 是不是有人搞破坏呀，不是作者删的呀



> 有人卖这个东西吗？

是的呢

**Comment by 86xqs** [comment]
脚本全废了，好像有人尝试恢复也没恢复过来。

**Comment by 86xqs** [comment]
搞不懂，谁都可以改吗

**Comment by githubwyj** [comment]
> 脚本全废了，好像有人尝试恢复也没恢复过来。

作者刚才好像回滚了,现在脚本还在

**Comment by 86xqs** [comment]
> > 脚本全废了，好像有人尝试恢复也没恢复过来。
> 
> 作者刚才好像回滚了,现在脚本还在

没用，我试过，一样不能运行

**Comment by HelloMark** [comment]
你的TG群还在吗？我的突然没了，不知道是不是被误T了

**Comment by 86xqs** [comment]
> > 脚本全废了，好像有人尝试恢复也没恢复过来。
> 
> 作者刚才好像回滚了,现在脚本还在

而且回滚的这位也不是作者吧

**Comment by githubwyj** [comment]
> 你的TG群还在吗？我的突然没了，不知道是不是被误T了

大家散了吧

**Comment by ivangreat** [comment]
回滚后的脚本可用，已鉴定。就是不知道为啥之前把代码全删了

**Comment by ashuai** [comment]
什么情况？吓得我赶紧fork了一份

**Comment by zdqd** [comment]
> 什么情况？吓得我赶紧fork了一份

lxk0301/jd_scripts备份。不要star。不要fork。谢谢配合。

唉，服

**Comment by xiezhouyan1027** [comment]
散了吧

**Comment by BIGBbox** [comment]
下载到自己的库去,别fork

**Comment by tomzhou98** [comment]
确实，自己用，或者无偿帮助伙伴使用都好，他妈的挂网上卖钱真是司马玩意儿

**Comment by smzcs** [comment]
这些比，大家都是搞软件的，缺咸鱼淘宝上面卖那点钱吗，到处贩卖全家肺炎

**Comment by githubwyj** [comment]
> 这些比，大家都是搞软件的，缺咸鱼淘宝上面卖那点钱吗，到处贩卖全家肺炎



> 确实，自己用，或者无偿帮助伙伴使用都好，他妈的挂网上卖钱真是司马玩意儿

反正现在淘宝闲鱼看到一个举报一个

**Comment by vvechan** [comment]
唉

**Comment by tomzhou98** [comment]
> > 这些比，大家都是搞软件的，缺咸鱼淘宝上面卖那点钱吗，到处贩卖全家肺炎
> 
> > 确实，自己用，或者无偿帮助伙伴使用都好，他妈的挂网上卖钱真是司马玩意儿
> 
> 反正现在淘宝闲鱼看到一个举报一个
淦。不搜不知道，一搜咸鱼这么多🐕

**Comment by bianodu** [comment]
> 你的TG群还在吗？我的突然没了，不知道是不是被误T了

TG群能分享下吗？我也想进，一直没找到组织

**Comment by githubwyj** [comment]
> > 你的TG群还在吗？我的突然没了，不知道是不是被误T了
> 
> TG群能分享下吗？我也想进，一直没找到组织

散了吧

**Comment by tofution** [comment]
> 回滚后的脚本可用，已鉴定。就是不知道为啥之前把代码全删了

怎么回滚？

**Comment by google-mirror** [comment]
傻子才去买, 京东加log验证了
